### ISSUE TITLE
Default service provider fails in Centos 6.6

### ISSUE THREAD

**Issue by xhujerr** [puppetlabs/puppetlabs-chronos#15]
Chronos service is managed by upstart. I'd like to add option $service_provider to reflect that.

Letting puppet select the provider was failing badly on CentOS 6.6. The default provider there is service, but chronos afaik requires upstart.

I'd like to have an option to enforce the provider. I don't know how to set some non-destructive default provider (for OSes which are not using upstart).

``` puppet

class chronos::service {
  ...
  $service_provider = $chronos::service_provider

  service { $service_name:
    ensure => running,
    enable => true,
    provider => $service_provider,
  }

```

**Comment by Ziaunys** [comment]
This is fixed in the master branch.
